########################################
# Environnement
########################################

# Dev environment
@baseUrl = http://localhost:8080
# Staging environment
#@baseUrl = https://products.localhost:5443

########################################
# Tests ProductResource V1
# IN MEMO ONLY
########################################

### GET all products V1
GET {{baseUrl}}/api/v1/products
Accept: application/json

### POST create product V1
POST {{baseUrl}}/api/v1/products
Content-Type: application/json

{
  "sku": "P001",
  "name": "Produit 1",
  "price": 12.5,
  "stock": 100
}

### POST create product V2
POST {{baseUrl}}/api/v1/products
Content-Type: application/json

{
  "sku": "P002",
  "name": "Produit 2",
  "price": 15.0,
  "stock": 10
}

### POST create product V1 conflict
POST {{baseUrl}}/api/v1/products
Content-Type: application/json

{
  "sku": "P001",
  "name": "Produit 1 bis",
  "price": 15.0,
  "stock": 50
}

########################################
# Tests ProductResource V2
########################################

### GET all products V2
GET {{baseUrl}}/api/v2/products
Accept: application/json

### GET product by SKU V2
GET {{baseUrl}}/api/v2/products/P001
Accept: application/json

### POST create product V2
POST {{baseUrl}}/api/v2/products
Content-Type: application/json

{
  "sku": "P002",
  "name": "Produit 2",
  "price": 20.0,
  "stock": 200
}

### DELETE product V2
DELETE {{baseUrl}}/api/v2/products/P002

########################################
# Tests ProductResource V3
########################################

### GET all products V3
GET {{baseUrl}}/api/v3/products
Accept: application/json

### GET product by SKU V3
GET {{baseUrl}}/api/v3/products/P001
Accept: application/json

### POST create product V3
POST {{baseUrl}}/api/v3/products
Content-Type: application/json

{
  "sku": "P003",
  "name": "Produit 3",
  "price": 30.0,
  "stock": 300
}

### DELETE product V3
DELETE {{baseUrl}}/api/v3/products/P003

########################################
# Tests ProductResource V4
########################################

### GET all products V4
GET {{baseUrl}}/api/v4/products
Accept: application/json

### GET product by SKU V4
GET {{baseUrl}}/api/v4/products/P001
Accept: application/json

### POST create product V4
POST {{baseUrl}}/api/v4/products
Content-Type: application/json

{
  "sku": "P004",
  "name": "Produit 4",
  "price": 40.0,
  "stock": 400
}

### DELETE product V4
DELETE {{baseUrl}}/api/v4/products/P004

########################################
# Tests ProductResource V5
########################################

### GET all products V5
GET {{baseUrl}}/api/v5/products
Accept: application/json

### GET product by SKU V5
GET {{baseUrl}}/api/v5/products/P001
Accept: application/json

### POST create product V5
POST {{baseUrl}}/api/v5/products
Content-Type: application/json

{
  "sku": "P005",
  "name": "Produit 5",
  "price": 50.0,
  "stock": 500
}

### DELETE product V5
DELETE {{baseUrl}}/api/v5/products/P005
